= Configure business application
:imagesdir: ..

There are several components that can be configured in the business application.
Depending on selected capabilities number of components can differ.

Entire configuration of the business application (service project) is done via application.properties
file that is a standard way to configure SpringBoot application. It is located under
`src/main/resources` of _{your business application}-service_

== Configuring core components

=== Configuring server

One of the most important confguration is actually the server itself. That is the host, port and path for the REST endpoints.

[source]
----
# used for server binding
server.address=localhost
server.port=8090

# used to define path for REST apis
cxf.path=/rest
----

=== Configuring execution server

Business application includes jBPM (KIE) execution server that can be configured to be better identified

[source]
----
kieserver.serverId=business-application-service
kieserver.serverName=business-application-service
kieserver.location=http://localhost:8090/rest/server
kieserver.controllers=http://localhost:8080/jbpm-console/rest/controller
----

*server id and server name* refers to how the business application will be identified when connecting to controller
(jbpm console) and thus should provide as meaningful information as possible.

*location* is used to inform other components that might interact with REST api where the server is accessible.
It could not be the exact same location as defined by server.address and server.port especially when running
in containers (Docker/OpenShift).

*controllers* allows to specify list (comma separated) of URLs.

=== Configuring capabilities

In case your business application selected 'Business Automation' as the capability then there you can control which of them
should actually be turned on on runtime.

[source]
----
# used for decision management
kieserver.drools.enabled=true
kieserver.dmn.enabled=true

# used for business processes and cases
kieserver.jbpm.enabled=true
kieserver.jbpmui.enabled=true
kieserver.casemgmt.enabled=true

# used for planning
kieserver.optaplanner.enabled=true
----

=== Configuring data source

NOTE: Data source configuration is only required for business automation (meaning when jBPM is used)

[source]
----
spring.datasource.username=sa
spring.datasource.password=sa
spring.datasource.url=jdbc:h2:./target/spring-boot-jbpm;MVCC=true
spring.datasource.driver-class-name=org.h2.Driver
----

Above configures the basic settings of the data source, next section will deal with
connection pooling for efficient data access.

NOTE: Depending on the driver class selected, make sure your application adds correct
dependency that include the JDBC driver class or data source class.

[source]
----
narayana.dbcp.enabled=true
narayana.dbcp.maxTotal=20
----

above is configuration that enables data source connection pool (that is based on
commons-dbcp2 project) and complete list of parameters can be found on
https://commons.apache.org/proper/commons-dbcp/configuration.html[configuration page].
All parameters from the configuration page must be prefixed with `narayana.dbcp.`


=== Configuring JPA

jBPM uses Hibernate as the data base access layer and thus needs to be properly configured

[source]
----
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect
spring.jpa.properties.hibernate.show_sql=false
spring.jpa.properties.hibernate.hbm2ddl.auto=update
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
----

NOTE: JPA configuration is completely based on SpringBoot so all options for both hibernate and
JPA can be found as https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#common-application-properties[SpringBoot configuration page]


=== Configuring jBPM executor

jBPM executor that is the backbone for asynchronous execution in jBPM is by default disabled.
It can be easily turned on by configuration parameters.

[source]
----
jbpm.executor.enabled=true
jbpm.executor.retries=5
jbpm.executor.interval=0
jbpm.executor.threadPoolSize=1
jbpm.executor.timeUnit=SECONDS
----

* *jbpm.executor.enabled* = true|false - allows to completely disable executor component
* *jbpm.executor.threadPoolSize* = Integer - allows to specify thread pool size where default is 1
* *jbpm.executor.retries* = Integer - allows to specify number of retries in case of errors while running a job
* *jbpm.executor.interval* = Integer - allows to specify interval (by default in seconds) that executor will use to synchronize with data base - default is 0 seconds which means it is disabled
* *jbpm.executor.timeUnit* = String - allows to specify timer unit used for calculating interval, value must be a valid constant of java.util.concurrent.TimeUnit, by default it's SECONDS.


=== Configuring distributed timers - Quartz

In case you plan to run your application in a cluster (multiple instances of it at the same time)
then you need to take into account timer service setup. Since the business application is running
on top of Tomcat web container the only option for timer service for distributed setup is Quartz based.

[source]
----
jbpm.quartz.enabled=true
jbpm.quartz.configuration=quartz.properties
----

Above are two mandatory parameters and the configuration file needs to either at classpath
or on the file system (if the path is given).

For distributed timers data base storage should be used and properly configured via
quartz.properties file.

By default Quartz requires two data sources

* managed data source so it can participate in transaction of the jBPM engine
* not managed data source so it can look up for timers to trigger without any transaction handling

jBPM based business application assumes that quartz data base (schema) will be collocated
with jBPM tables and by that produces data source used for transactional operations for Quartz.

The other (non transactional) data source needs to be configured but it should point
to the same data base as the main data source.

[source]
----
# enable to use data base as storage
jbpm.quartz.db=true

quartz.datasource.name=quartz
quartz.datasource.username=sa
quartz.datasource.password=sa
quartz.datasource.url=jdbc:h2:./target/spring-boot-jbpm;MVCC=true
quartz.datasource.driver-class-name=org.h2.Driver

# used to configure connection pool
quartz.datasource.dbcp2.maxTotal=15

# used to initialize quartz schema
quartz.datasource.initialization=true
spring.datasource.schema=classpath*:quartz_tables_h2.sql
spring.datasource.initialization-mode=always
----

The last three lines of the above configuration is responsible for initializing
database schema automatically. When configured it should point to a proper
DDL script.

=== Configuring different data bases

Business application is generated with default H2 database - just to get started quickly
and without any extra requirements. But certainly this is not valid for production use.

Luckily, business application that are generated (from the archetype) come with
configuration dedicated to

* MySQL
* PostgreSQL

There are dedicated profiles - both maven and spring to get you started
really fast without much of work. The only thing you need to do is to alight the
configuration with your data bases.

MySQL configuration

[source]
----
spring.datasource.username=jbpm
spring.datasource.password=jbpm
spring.datasource.url=jdbc:mysql://localhost:3306/jbpm
spring.datasource.driver-class-name=com.mysql.jdbc.jdbc2.optional.MysqlXADataSource

#hibernate configuration
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL5InnoDBDialect
----

PostgreSQL configuration

[source]
----
spring.datasource.username=jbpm
spring.datasource.password=jbpm
spring.datasource.url=jdbc:postgresql://localhost:5432/jbpm
spring.datasource.driver-class-name=org.postgresql.xa.PGXADataSource

#hibernate configuration
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
----

Once the updates to the configuration are done you can launch your application via

`./launch.sh clean install -Pmysql` for MySQL on Linux/Unix

`./launch.bat clean install -Pmysql` for MySQL on Windows


`./launch.sh clean install -Ppostgres` for MySQL on Linux/Unix

`./launch.bat clean install -Ppostgres` for MySQL on Windows
